# Generated by Django 3.1.8 on 2022-09-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0004_redirectitem_errorcorrectionlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectitem',
            name='secret',
            field=models.CharField(max_length=100),
        ),
    ]
